# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Park.destroy_all
Photo.destroy_all
User.destroy_all

# User Section
@SteveStrum = User.create!(username: "SteveStrum", email: 'stevenstrum@email.com', password: "SteveStrum")
@FrankStrum = User.create!(username: "FrankStrum", email: 'frankstrum@email.com', password: "FrankStrum")
@KikiOrtiz = User.create!(username: "KikiOrtiz", email: 'kikiortiz@email.com', password: "KikiOrtiz")
@DonnaStrum = User.create!(username: "DonnaStrum", email: 'donnastrum@email.com', password: "DonnaStrum")
@RalphStrum = User.create!(username: "RalphStrum", email: 'ralphstrum@email.com', password: "RalphStrum")

puts "#{User.count} users created"

# Photo Section 
Photo.create!(title: 'Who Wants a balloon? Seriously I have way to many.', user: @SteveStrum, img_url: 'https://images.pexels.com/photos/3526067/pexels-photo-3526067.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Photo.create!(title: 'Wait did you know Goofy was a cow? I know this is pluto who is a dog but common.', user: @SteveStrum, img_url: 'https://images.pexels.com/photos/3411134/pexels-photo-3411134.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Photo.create!(title: 'Enjoy the wild west where well people were kinda, I guess you would say, wild!', user: @SteveStrum, img_url: 'https://images.pexels.com/photos/5259755/pexels-photo-5259755.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Photo.create!(title: 'Roar!', user: @SteveStrum, img_url: 'https://images.unsplash.com/photo-1519939040527-1753e8b6b9d1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1356&q=80')
Photo.create!(title: 'Epcot is Heaven on Earth', user: @SteveStrum, img_url: 'https://images.unsplash.com/photo-1609653978777-f065cb17df97?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80')
Photo.create!(title: 'The Dark Side is back', user: @FrankStrum, img_url: 'https://images.pexels.com/photos/4415060/pexels-photo-4415060.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Photo.create!(title: 'Ten-hut Andys Mom is on her way', user: @FrankStrum, img_url: 'https://images.unsplash.com/photo-1557159437-0dc55fdcc7c3?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80')
Photo.create!(title: 'Wow that is one really great big ball!', user: @FrankStrum, img_url: 'https://images.unsplash.com/photo-1610305013822-ad68befe3550?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1951&q=80')
Photo.create!(title: 'I tried climbing the temple security wasnt happy', user: @FrankStrum, img_url: 'https://www.wdwinfo.com/wp-content/uploads/2018/09/mexico.png')
Photo.create!(title: 'My favorite park!', user: @FrankStrum, img_url: 'https://images.pexels.com/photos/4415058/pexels-photo-4415058.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Photo.create!(title: 'The scenary is absolutely amazing', user: @FrankStrum, img_url: 'https://2traveldads.com/wp-content/uploads/Floating-mountains-of-Pandora-Disneys-Animal-Kingdom-Disney-World-Orlando-Florida-5.jpg')
Photo.create!(title: 'Follow me Mickey', user: @FrankStrum, img_url: 'https://images.unsplash.com/photo-1484923720570-4bc210954735?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80')
Photo.create!(title: 'Time to be a kid again and win a minion! BANANA!!!!', user: @KikiOrtiz, img_url: 'https://images.pexels.com/photos/203561/pexels-photo-203561.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Photo.create!(title: 'I now understand why they call Disney world the most magical place on earth ', user: @KikiOrtiz, img_url: 'https://images.pexels.com/photos/3411132/pexels-photo-3411132.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Photo.create!(title: 'Cant wait to eat!', user: @KikiOrtiz, img_url: 'https://orlandoinsidervacations.com/wp-content/uploads/world-showcase-china.jpg')
Photo.create!(title: 'Epcot has rides too', user: @KikiOrtiz, img_url: 'https://www.micechat.com/wp-content/uploads/2020/01/IMG_4618.jpg')
Photo.create!(title: 'Its the circle of LIFE', user: @KikiOrtiz, img_url: 'https://sir.wdwnt.com/wdwnt.com/2018/06/Tree-of-Life-Blue-Skies.jpg')
Photo.create!(title: 'WELCOME TO THE TWILIGHT ZONE! GOODBYE', user: @KikiOrtiz, img_url: 'https://images.unsplash.com/photo-1465520873236-ce7c931bba93?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1354&q=80')
Photo.create!(title: 'Cheerio mate lets go to the Emporium in our fancy car.', user: @DonnaStrum, img_url: 'https://res.cloudinary.com/twenty20/private_images/t_standard-fit/v1521838756/photosp/3775661b-cd20-4f94-85e4-f7acf5191b9f/3775661b-cd20-4f94-85e4-f7acf5191b9f.jpg')
Photo.create!(title: 'Please dont step on me', user: @DonnaStrum, img_url: 'https://images.unsplash.com/photo-1599793688968-df40eb66de6b?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1489&q=80')
Photo.create!(title: 'Eve is that you? ', user: @DonnaStrum, img_url: 'https://images.unsplash.com/photo-1605493666596-f605022f28ce?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80')
Photo.create!(title: 'Knock knock? who is there? Me ? Me who ? arent you glad I didnt scare you?', user: @DonnaStrum, img_url: 'https://res.cloudinary.com/twenty20/private_images/t_standard-fit/v1521838891/photosp/d9a87c28-c647-435b-ae9e-7cfae5bbdb30/d9a87c28-c647-435b-ae9e-7cfae5bbdb30.jpg')
Photo.create!(title: 'Mickey looks different in October', user: @DonnaStrum, img_url: 'https://blog-cdn.touringplans.com/blog/wp-content/uploads/2020/09/Halloween-Decorations-at-Magic-Kingdom-2020-scaled-e1600221044449-656x700.jpg')
Photo.create!(title: 'A perfect picture!', user: @DonnaStrum, img_url: 'https://3.bp.blogspot.com/-si2GpJ2Iwgo/Ua448BtGdRI/AAAAAAAAAtU/q5Y0IiwpEIA/s1600/Magic+Kingdom+2013+003.JPG')
Photo.create!(title: 'Mike Wazowski', user: @RalphStrum, img_url: 'http://blog.touringplans.com/wp-content/uploads/2013/06/111.jpg')
Photo.create!(title: 'O\' Canada', user: @RalphStrum, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2017/03/cmtp379580.jpg')
Photo.create!(title: 'The beauty and the beast never looked so spectacular', user: @RalphStrum, img_url: 'https://images.unsplash.com/photo-1585243532922-5e061be22d54?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1350&q=80')
Photo.create!(title: 'Tttttrasshhhh, how am I alive ......', user: @RalphStrum, img_url: 'https://images.unsplash.com/photo-1615493749953-742903db7e9d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1488&q=80')
Photo.create!(title: 'I will 100% be your guest, thank you for asking!', user: @RalphStrum, img_url: 'https://www.disneyfoodblog.com/wp-content/uploads/2012/11/Be-Our-Guest-Bridge-Entrance.jpg')
Photo.create!(title: 'Look at the adorable couple, or are they married, well whatever they look so happy', user: @RalphStrum, img_url: 'https://images.pexels.com/photos/6921010/pexels-photo-6921010.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')


puts "#{Photo.count} photos created"

# Park Section

@MagicKingdom = Park.create!(name: 'Magic Kingdom', img_url: 'https://images.unsplash.com/photo-1556950961-8c092986258e?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=700&q=80')
@HollywoodStudios = Park.create!(name: 'Hollywood Studios', img_url: 'https://pbs.twimg.com/media/D1ytbQwX4AE2Lxt.jpg')
@Epcot = Park.create!(name: 'Epcot', img_url: 'https://images.unsplash.com/photo-1553526630-81e8f0d6ffde?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80')
@AnimalKingdom = Park.create!(name: 'Animal Kingdom', img_url: 'https://images.unsplash.com/photo-1522008629172-0c17aa47d1ee?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80')

puts "#{Park.count} parks created"

# Ride Section
#Magic Kingdom rides
Ride.create!(name: 'It\'s a Small World', park: @MagicKingdom, img_url: 'https://secure.parksandresorts.wdpromedia.com/resize/mwImage/1/630/354/90/wdpromedia.disney.go.com/media/wdpro-assets/parks-and-tickets/attractions/magic-kingdom/its-a-small-world/its-a-small-world-00.jpg?23052012090830', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Astro Orbiter', park: @MagicKingdom, img_url: 'https://www.orlandofuntickets.com/common_resources/images/1ec5721c4173e8d89256da7a37bd2682.jpg', category: 'Spinning', height: 'Any Height')
Ride.create!(name: 'Big Thunder Mountain Railrod', park: @MagicKingdom, img_url: 'https://live.staticflickr.com/2520/4222457526_8461837dc6_b.jpg', category: 'Thrill', height: '40in (102cm) or taller')
Ride.create!(name: 'Buzz Lightyear\'s Space Ranger Spin', park: @MagicKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/parks-and-tickets/attractions/magic-kingdom/buzz-lightyears-space-ranger-spin/buzz-lightyear-space-ranger-spin-00.jpg?1559892286107', category: 'Spinning', height: 'Any Height')
Ride.create!(name: 'Country Bear Jamboree', park: @MagicKingdom, img_url: 'https://sir.wdwnt.com/wdwnt.com/2020/12/Country-Bear-Jamboree-Tokyo-Disneyland-Five-Bear-Rugs-4621269-scaled.jpeg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Dumbo the Flying Elephant', park: @MagicKingdom, img_url: 'https://mickeyblog.com/wp-content/uploads/2017/07/Dumbo-Ride-at-Magic-Kingdom.jpg', category: 'Spinning', height: 'Any Height')
Ride.create!(name: 'Jungle Cruise', park: @MagicKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2016/07/skjr313.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Liberty Square Riverboat', park: @MagicKingdom, img_url: 'https://blogmickey.com/wp-content/uploads/2018/04/liberty-square-riverboat-00.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Mad Tea Party', park: @MagicKingdom, img_url: 'https://cache.undercovertourist.com/media_file/mad-tea-party-8625.jpg', category: 'Spinning', height: 'Any Height')
Ride.create!(name: 'Mickey\'s PhilharMagic', park: @MagicKingdom, img_url: 'https://www.disneyfanatic.com/wp-content/uploads/2016/05/Castle_Philarmagic_MCP.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Peter Pan\'s Flight', park: @MagicKingdom, img_url: 'https://media1.tokyodisneyresort.jp/images/adventure/attraction/521_main_visual_name_1.jpg?mod=20201207122747', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Pirates of the Caribbean', park: @MagicKingdom, img_url: 'https://www.disneyfoodblog.com/wp-content/uploads/2020/05/%C2%A9Disney-Pirates-of-the-Caribbean-13.png', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Prince Charming Regal Carrousel', park: @MagicKingdom, img_url: 'http://3.bp.blogspot.com/-HdsL8An2hB4/Ubizh_tgSLI/AAAAAAAABEY/1aTz8xq1b6U/s1600/12-25-08+Carousel+8.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Seven Dwarfs Mine Train', park: @MagicKingdom, img_url: 'https://mickeyblog.com/wp-content/uploads/2017/09/Seven-Dwarfs-Mine-Train-720x340.jpg', category: 'Thrill', height: '38in (97cm) or taller')
Ride.create!(name: 'Space Mountain', park: @MagicKingdom, img_url: 'https://www.fodors.com/assets/destinations/710641/space-mountain-walt-disney-world-orlando-florida-usa_main.jpg', category: 'Thrill', height: '44in (113cm) or taller')
Ride.create!(name: 'Splash Mountain', park: @MagicKingdom, img_url: 'https://magicinsiders.com/wp-content/uploads/2019/04/how-scary-is-splash-mountain-cover.jpg', category: 'Thrill', height: '40in (102cm) or taller')
Ride.create!(name: 'The Barnstormer', park: @MagicKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/630/354/90/media/disneyparksjapan-prod/disneyparksjapan_v0001/1/media/wdw/attractions/barnstormer-starring-great-goofini-00.jpg', category: 'Thrill', height: '35in (89cm) or taller')
Ride.create!(name: 'Haunted Mansion', park: @MagicKingdom, img_url: 'https://i.redd.it/2a931xckqdzx.jpg', category: 'Thrill', height: 'Any Height')
Ride.create!(name: 'The Magic Carpets of Aladdin', park: @MagicKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2015/07/ADMCOA3589351.jpg', category: 'Spinning', height: 'Any Height')
Ride.create!(name: 'The Many Adventures of Winnie the Pooh', park: @MagicKingdom, img_url: 'https://cache.undercovertourist.com/media_file/the-many-adventures-of-winnie-the-pooh-12408.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Tom Sawyer Island', park: @MagicKingdom, img_url: 'https://i.ytimg.com/vi/PU04E1Hbcjo/maxresdefault.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Tomorrowland Speedway', park: @MagicKingdom, img_url: 'https://i.pinimg.com/originals/bf/08/33/bf083368149426b9619788f36a1161d1.jpg', category: 'Thrill', height: '32in (82cm) or taller')
Ride.create!(name: 'Under the Sea ~ Journey of The Little Mermaid', park: @MagicKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/630/354/90/media/disneyparksjapan-prod/disneyparksjapan_v0001/1/media/wdw/attractions/under-the-sea-journey-of-the-little-mermaid-new-00.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Walt Disney\'s Enchanted Tiki Room', park: @MagicKingdom, img_url: 'http://www.wdw-magazine.com/wp-content/uploads/2017/08/ATTRACTION-1-CLIFF.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Swiss Family Treehouse', park: @MagicKingdom, img_url: 'https://insidethemagic-119e2.kxcdn.com/wp-content/uploads/2019/12/Screen-Shot-2019-12-23-at-7.57.49-PM.png', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Walt Disney World Railroad - Fantasyland', park: @MagicKingdom, img_url: 'https://d3bo0mk5kk7egf.cloudfront.net/imgstore/ElementGalleryItems/attractions/Fullsize/Walt-Disney-World-Railroad_Full_8134.jpg?width=2280&quality=60&encoder=freeimage&progressive=true', category: 'Fun for all', height: 'Any Height')
Ride.create!(name: 'Monsters, Inc. Laugh Floor', park: @MagicKingdom, img_url: 'https://d23.com/app/uploads/2017/03/1180w-600h_040217_monsters-inc-laugh-floor-780x440.jpg', category: 'Fun for all', height: 'Any Height')
Ride.create!(name: 'A Pirate\'s Adventure ~ Treasures of the Seven Seas', park: @MagicKingdom, img_url: 'https://cache.undercovertourist.com/media_file/pirates-adventure-treasures-seven-seas-9654.jpg', category: 'Fun for all', height: 'Any Height')
Ride.create!(name: 'Frontierland Shootin\' Arcade', park: @MagicKingdom, img_url: 'https://celebrationspress.com/wp-content/uploads/2019/05/Screenshot-2019-05-11-at-10.09.27-PM-Edited.png', category: 'Fun for all', height: 'Any Height')
#Hollywood Studios Rides
Ride.create!(name: 'Alien Swirling Saucers', park: @HollywoodStudios, img_url: 'https://wdwnt.com/wp-content/uploads/2018/06/0622ZS_0332b.jpg', category: 'Spinning', height: '32in (82cm) or taller')
Ride.create!(name: 'Lightning McQueen\'s Racing Academy', park: @HollywoodStudios, img_url: 'https://travelbypixiedust.com/wp-content/uploads/2019/04/img_4085-1-scaled.jpg', category: 'Fun for all', height: 'Any Height')
Ride.create!(name: 'Mickey & Minnie\'s Runaway Railway', park: @HollywoodStudios, img_url: 'https://insidethemagic-119e2.kxcdn.com/wp-content/uploads/2020/02/underwater-mickey-minnie-runaway-16x9-1.jpg', category: 'Fun for all', height: 'Any Height')
Ride.create!(name: 'Millennium Falcon: Smugglers Run', park: @HollywoodStudios, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/630/354/90/media/disneyparksjapan-prod/disneyparksjapan_v0001/1/media/dlr/destinations/smugglers-run-interior-16x9.jpg', category: 'Thrill', height: '38in (97cm) or taller')
Ride.create!(name: 'Muppet Vision 3D', park: @HollywoodStudios, img_url: 'https://i1.wp.com/www.toughpigs.com/wp-content/uploads/2014/11/muppetv.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Rock and Roll Roller Coaster Starring Aerosmith', park: @HollywoodStudios, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2014/07/ROCKCOA1564614521.jpg', category: 'Thrill', height: '48in (122cm) or taller')
Ride.create!(name: 'Slinky Dog Dash', park: @HollywoodStudios, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1920/1080/75/dam/disney-world/destinations/hollywood-studios/toy-story-land/toy-story-slinky-dog-ride-16x9.jpg?1573141195342', category: 'Thrill', height: '38in (97cm) or taller')
Ride.create!(name: 'Star Tours - The Adventures Continue', park: @HollywoodStudios, img_url: 'https://i.ytimg.com/vi/sfxOeojzHI0/maxresdefault.jpg', category: 'Thrill', height: '40in (102cm) or taller')
Ride.create!(name: 'The Twilight Zone Tower of Terror', park: @HollywoodStudios, img_url: 'https://d23.com/app/uploads/2019/07/1180w-600h_072219_tower-of-terror-fun-facts-780x440.jpg', category: 'Thrill', height: '40in (102cm) or taller')
Ride.create!(name: 'Toy Story Mania', park: @HollywoodStudios, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2011/12/tsm0129121LARGE.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Vacation Fun - An Original Animated Short with Mickey & Minnie', park: @HollywoodStudios, img_url: 'https://mickeyblog.com/wp-content/uploads/2019/12/JUST_ANNOUNCED_Mickey_Shorts_Theater_Debuts_March_2020_in_Disney%E2%80%99s_Hollywood_Studios_Disney_Parks_Blog_-_2019-12-03_20.52.57-1.png', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Star Wars: Rise of the Resistance', park: @HollywoodStudios, img_url: 'https://www.channelnewsasia.com/image/11098462/1x1/600/600/229e268a456d74a444bc1e91446941d7/rE/star-wars-galaxy-s-edge.jpg', category: 'Thrill', height: '40in (102cm) or taller')
Ride.create!(name: 'Star Wars Launch Bay', park: @HollywoodStudios, img_url: 'https://cdn-0.disneytips.com/wp-content/uploads/2015/09/HS_StarWarsLaunchBay_Troopers-620x330.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Walt Disney Presents', park: @HollywoodStudios, img_url: 'https://allears.net/wp-content/uploads/2018/11/Hollywood-Studios-Attraction-Sign-walt-disney-presents-002.jpg', category: 'Fun for All', height: 'Any Height')
#Animal Kingdoms Rides
Ride.create!(name: 'Avatar Flight of Passage', park: @AnimalKingdom, img_url: 'https://www.wdw-magazine.com/wp-content/uploads/2020/09/flight-of-passage-mike-billick.jpg', category: 'Thrill', height: '44in (113cm) or taller')
Ride.create!(name: 'DINOSAUR', park: @AnimalKingdom, img_url: 'https://cdn.vox-cdn.com/thumbor/QPSpwOh2ZtDQsXu0V78atbYKCXE=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/19545811/dinosaur_00.jpg', category: 'tHRILL', height: '40IN (102cm) or taller')
Ride.create!(name: 'Discovery Island Trails', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/parks-and-tickets/attractions/animal-kingdom/discovery-island-trails/discovery-island-trails-00.jpg?1569604340414', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Epedition Everest Legend of the Forbidden Mountain', park: @AnimalKingdom, img_url: 'https://blog-cdn.touringplans.com/blog/wp-content/uploads/2015/10/Expedition-Everest-2-700x465.jpg', category: 'Thrill', height: '44in (113cm) or taller')
Ride.create!(name: 'It\'s Tough to be a Bug!', park: @AnimalKingdom, img_url: 'https://cache.undercovertourist.com/media_file/its-tough-to-be-a-bug-6818.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Kali River Rapids', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/630/354/90/media/disneyparksjapan-prod/disneyparksjapan_v0001/1/media/wdw/attractions/kali-river-rapids-00.jpg', category: 'Thrill', height: '38in (97cm) or taller')
Ride.create!(name: 'Kilimanjaro Safaris', park: @AnimalKingdom, img_url: 'https://i.ytimg.com/vi/2M8Z6ILuGqA/hqdefault.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Maharajah Jungle Trek', park: @AnimalKingdom, img_url: 'https://wdwprepschool.com/wp-content/uploads/maharajahjungletrek.jpg', category: '', height: '')
Ride.create!(name: 'Na\'vi River Journey', park: @AnimalKingdom, img_url: 'http://diskingdom.com/wp-content/uploads/2016/02/Screen-Shot-2016-02-16-at-12.59.20-AM.png', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'The Oasis Exibits', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/attractions/animal-kingdom/roseate-spoonbill-16x9.jpg?1576170116767', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'TirceraTop Spin', park: @AnimalKingdom, img_url: 'https://amusementparksorlando.com/wp-content/uploads/triceratop-spin-500.jpg', category: 'Spinning', height: 'Any Height')
Ride.create!(name: 'Wilderness Explorers', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/gallery/attractions/animal-kingdom/wilderness-explorers/wilderness-explorers-gallery00.jpg?1559891895890', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Wildlife Express Train', park: @AnimalKingdom, img_url: 'https://www.laughingplace.com/w/wp-content/uploads/2019/04/A-713.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Affection Section', park: @AnimalKingdom, img_url: 'https://secure.cdn1.wdpromedia.com/resize/mwImage/1/410/205/75/dam/wdpro-assets/parks-and-tickets/attractions/animal-kingdom/affection-section/affection-section-00.jpg?1540237951578', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'African Birds - Disney Animals', park: @AnimalKingdom, img_url: 'https://i.pinimg.com/originals/ea/d6/d1/ead6d1c86c0451fee7f1106f0ebc78d3.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'African Elephants - Disney Animals', park: @AnimalKingdom, img_url: 'http://1.bp.blogspot.com/-8W7IW5OL1vg/U43Ox9DPVII/AAAAAAAACtI/g_6NJ61Tra0/s1600/DSC_0796.JPG', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'African Hogs - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/attractions/animal-kingdom/disney-animals-african-hogs/warthog-pair-in-burrow-16x9.jpg?1573162886887', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'African Lions - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1920/1080/75/dam/wdpro-assets/parks-and-tickets/attractions/animal-kingdom/disney-animals/disney-animals-lions/disney-animals-lions-00-b.jpg?1565294113698', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Ankole Cattle - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/attractions/animal-kingdom/disney-animals-ankole-watusi/wild-africa-trek-cattle-16x9.jpg?1575390128125', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Asian Small-Clawed Otters - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/attractions/animal-kingdom/disney-animals-otters/two-otthers-water-16x9.jpg?1569596088290', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Butterflies -Disney Animals', park: @AnimalKingdom, img_url: 'https://www.wildgratitude.com/wp-content/uploads/2015/08/butterfly-spirit-animal.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Conservation Station', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/gallery/attractions/animal-kingdom/conservation-station/conservation-station-gallery00.jpg?1563918721614', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Cotton-Top Tarmarins - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2011/07/tam234234LARGE.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Dino-Sue', park: @AnimalKingdom, img_url: 'https://thumb.spokesman.com/RAJHnoQECKjPOyHmDMkOzdiHlUQ=/1200x0/media.spokesman.com/photos/2020/08/11/LedeSueImage.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Flamingos - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/434/244/75/dam/wdpro-assets/parks-and-tickets/attractions/animal-kingdom/disney-animals/disney-animals-flamingos-flock-gathering-water-16x9.jpg?1615226571387', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Fossil Fun Games', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/gallery/attractions/animal-kingdom/fossil-fun-games/fossil-fun-games-gallery00.jpg?1551208966418', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Gibbons - Disney Animals', park: @AnimalKingdom, img_url: 'https://res.cloudinary.com/roundglass/image/upload/v1564043766/roundglass/sustain/Gibbon_Dhritiman-Mukherjee_oya26j.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Giraffes - Disney Animals', park: @AnimalKingdom, img_url: 'http://www.floribobs.com/images/disney-animals-giraffes-00.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Gorillas - Disney Animals', park: @AnimalKingdom, img_url: 'https://photos.smugmug.com/MISCELLANEOUS/Miscellaneous-4-COVID-19/i-cMpmgWw/0/a8ebedd1/O/zawadi_staring_silve_IVRAG.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Hippopotamuses - Disney Animals', park: @AnimalKingdom, img_url: 'http://www.insidethemagic.net/wp-content/uploads/2018/01/hippoAK-550x309.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Invertebrates - Disney Animals', park: @AnimalKingdom, img_url: 'http://www.floribobs.com/images/invertebrates-mexican-red-knee-tarantula-16x9.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Komodo Dragons - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/attractions/animal-kingdom/disney-animals-komodo-dragons/komodo-dragon-close-up-16x9.jpg?1575380175022', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Meerkats - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/attractions/animal-kingdom/disney-animals-meerkats/meerkat-closeup-16x9.jpg?1574781274493', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Migratory Birds - Disney Animals', park: @AnimalKingdom, img_url: 'http://www.floribobs.com/images/disney-animals-migratory-birds-00.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Okapis - Disney Animals', park: @AnimalKingdom, img_url: 'http://www.floribobs.com/images/disney-animals-okapis-00.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Rhinos - Disney Animals', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2013/11/0820BZ_7152TA.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Tigers - Disney Animals', park: @AnimalKingdom, img_url: 'http://www.floribobs.com/images/disney-animals-asian-sumatran-tigers-00.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Tree of Life', park: @AnimalKingdom, img_url: 'https://upload.wikimedia.org/wikipedia/en/9/9a/Disney_Animal_Kingdom_%2827589660700%29.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Vultures - Disney Animals', park: @AnimalKingdom, img_url: 'http://www.floribobs.com/images/disney-animals-vultures-00-vultures-walking-at-DAKL-with-wings-out-16x9.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Zebras - Disney Animals', park: @AnimalKingdom, img_url: 'https://media1.fdncms.com/orlando/imager/u/original/14733087/eiyrtuuhfsjdkfhd246554-768x461.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'The Boneyard', park: @AnimalKingdom, img_url: 'https://insidethemagic-119e2.kxcdn.com/wp-content/uploads/2018/05/Screen-Shot-2018-05-25-at-7.32.55-PM.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Disney\'s Animal Kingdom Theme Park at Night', park: @AnimalKingdom, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/434/244/75/dam/wdpro-assets/parks-and-tickets/attractions/animal-kingdom/animal-kingdom-night/tree-of-life-purple-17.jpg?1614975838077', category: 'Fun for All', height: 'Any Height')
#Epcot Rides
Ride.create!(name: 'Awesome Planet', park: @Epcot, img_url: 'https://allears.net/wp-content/uploads/2020/01/2020-wdw-epcot-the-land-pavilion-awesome-planet-opening-day.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Canada Far and Wide in Circle-Vision 360', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/attractions/epcot/canada-far-and-wide/canada-far-and-wide-16x9.jpg?1613071634869', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Disney and Pixar Short Film Festival', park: @Epcot, img_url: 'https://www.disneylists.com/wp-content/uploads/2017/02/Featured-Pixar-Film.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Frozen Ever After', park: @Epcot, img_url: 'https://miro.medium.com/max/4000/1*eKhIvdfv6XP9bzBF3CJQ6Q.jpeg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Gran Fiesta Tour Starring The Three Caballeros', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2019/01/ksodjfgivfbgfdkgbdhsj483.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Impressions de France', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2016/06/IDF387629FI.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Journey Into Imagination With Figment', park: @Epcot, img_url: 'https://cache.undercovertourist.com/media_file/journey-into-imagination-with-figment-12622', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Kidcot Fun Stops', park: @Epcot, img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYS6bBJ56GbIVxJ6aHRw95KKpWLcQBOMnPew&usqp=CAU', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Living with the Land', park: @Epcot, img_url: 'https://insidethemagic-119e2.kxcdn.com/wp-content/uploads/2019/08/living-with-the-land.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Mission: SPACE', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/media/blog/wp-content/uploads/2017/05/sdawdw38975811.jpg', category: 'Spinning', height: '40in (102cm) or taller')
Ride.create!(name: 'Reflections of China', park: @Epcot, img_url: 'https://thedisneyblog.com/wp-content/uploads/2017/07/reflections-of-china-gallery00.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Soarin\' Around the World', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/gallery/attractions/epcot/soarin/soarin-gallery07.jpg?1559892150947', category: 'Thrill', height: '40in (102cm) or taller')
Ride.create!(name: 'Spaceship Earth', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/gallery/attractions/epcot/spaceship-earth/spaceship-earth-gallery00.jpg?1559892180952', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Test Track', park: @Epcot, img_url: 'https://secure.cdn1.wdpromedia.com/resize/mwImage/1/1920/1080/75/dam/wdpro-assets/gallery/attractions/epcot/test-track/test-track-gallery14.jpg?1520567564054', category: 'Thrill', height: '40in (102cm) or taller')
Ride.create!(name: 'The American Adventure', park: @Epcot, img_url: 'https://www.disneyfanatic.com/wp-content/uploads/2015/07/AmericanAdventure3.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'The Seas with Nemo & Friends', park: @Epcot, img_url: 'https://cache.undercovertourist.com/media_file/the-seas-with-nemo-and-friends-8574.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Walt Disney Imagineering presents the Epcot Experience', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/410/205/75/dam/disney-world/attractions/epcot/epcot-experience/epcot-experience-center-render-16x9.jpg?1569933168232', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'American Heritage Gallery', park: @Epcot, img_url: 'https://secure.cdn1.wdpromedia.com/resize/mwImage/1/1920/1080/75/dam/disney-world/attractions/epcot/american-heritage-gallery/american-heritage-adventure-display-16x9.jpg?1532711071424', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Bijutsu-kan Gallery', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1920/1080/75/dam/wdpro-assets/gallery/attractions/epcot/bijutsu-kan-gallery/bijutsu-kan-gallery-gallery00.jpg?1583972506767', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Coral Reefs - Disney Animals', park: @Epcot, img_url: 'https://i.pinimg.com/originals/b4/ee/6c/b4ee6c7b019aac38a892f23d302ce424.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Gallery of Arts and History', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1920/1080/75/dam/disney-world/attractions/epcot/gallery-arts-and-history/gallery-of-arts-history-race-the-sun-sign-16x9.jpg?1574449821336', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'House of the Whispering Willows', park: @Epcot, img_url: 'https://cache.undercovertourist.com/media_file/house-of-the-whispering-willows-934462-16dd5efd4a6.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'ImageWorks - The "What If" Labs', park: @Epcot, img_url: 'https://www.laughingplace.com/w/wp-content/uploads/2019/04/A-725.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Leave A Legacy', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/attractions/epcot/leave-a-legacy/lal-lrg-16x9.jpg?1612879865771', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Manatees - Disney Animals', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1920/1080/75/dam/disney-world/attractions/epcot/disney-animals-manatees/west-indian-manatee-littlejoe-1-16x9.jpg?1575485855086', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Mexico Folk Art Gallery', park: @Epcot, img_url: 'https://cache.undercovertourist.com/media_file/mexico-folk-art-gallery-934464-16dd5fbb317.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Palais du Cinema', park: @Epcot, img_url: 'https://sir.wdwnt.com/wdwnt.com/2020/01/87D9F886-76A3-4D3F-982C-4A0DAEB30CCE.jpeg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Reef Fish - Disney Animals', park: @Epcot, img_url: 'http://www.floribobs.com/images/reef-fish-tang-blue-acanthurus-16x9.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'SeaBase', park: @Epcot, img_url: 'https://media-cdn.tripadvisor.com/media/photo-m/1280/19/6c/82/05/seabase-bruce-s-sub-house.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Sea Turtles - Disney Animals', park: @Epcot, img_url: 'https://www.theregreview.org/wp-content/uploads/2017/04/sea-turtle.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Sharks and Rays - Disney Animals', park: @Epcot, img_url: 'http://www.floribobs.com/images/disney-animals-sharks-00.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Stave Church Gallery', park: @Epcot, img_url: 'https://attractionsmagazine.com/wp-content/uploads/2018/03/stave-church-2.jpeg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Advanced Training Lab', park: @Epcot, img_url: 'https://803277.smushcdn.com/1580116/wp-content/uploads/2019/04/A-746.jpg?lossy=0&strip=0&webp=1', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Bruce\'s Shark World', park: @Epcot, img_url: 'https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/parks-and-tickets/attractions/epcot/bruces-shark-world/bruces-shark-world-01.jpg?1573158254529', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Remy\'s Ratatouille Adventure', park: @Epcot, img_url: 'https://insidethemagic-119e2.kxcdn.com/wp-content/uploads/2020/01/ratatouille-550x331.jpg', category: 'Fun for All', height: 'Any Height')
Ride.create!(name: 'Turtle Talk With Crush', park: @Epcot, img_url: 'https://howtodisney.com/wp-content/uploads/2017/02/turtle-talk-with-crush-00_Disney.jpg', category: 'Fun for All', height: 'Any Height')

puts "#{Ride.count} rides created"
